# Generated by Django 5.2.8 on 2025-12-09 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTCode',
            fields=[
                ('gst_id', models.AutoField(primary_key=True, serialize=False)),
                ('gst_code', models.CharField(max_length=20, unique=True)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gst_entries_added', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_gst_codes',
                'ordering': ['-gst_id'],
            },
        ),
    ]
