# Generated by Django 5.2.8 on 2025-12-13 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admincontract',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='control_panel.admin'),
        ),
        migrations.AddField(
            model_name='admincontract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminservice',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_services', to='control_panel.admin'),
        ),
        migrations.AddField(
            model_name='adminservice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargerule',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_charge_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositbankaccount',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_banks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositbankaccount',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_banks_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funddepositrequest',
            name='linked_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requests', to='control_panel.depositbankaccount'),
        ),
        migrations.AddField(
            model_name='gstcode',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gst_entries_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstcode',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_entries_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionalfee',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.gstcode'),
        ),
        migrations.AddField(
            model_name='admin',
            name='registered_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.location'),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members_created_by_me', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='paymentgatewaybank',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts_added', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='paymentgatewaybank',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_modified', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='memberactionlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='gltrn',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='funddepositrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_requests_reviewed', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='funddepositrequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_requests_made', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluserbalance',
            name='user',
            field=models.OneToOneField(blank=True, db_column='portal_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_account', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluserinfo',
            name='city_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='control_panel.location'),
        ),
        migrations.AddField(
            model_name='portaluserinfo',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_created', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluserinfo',
            name='hierarchy_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluserinfo',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_details', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluserinfo',
            name='state_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='control_panel.region'),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='control_panel.region'),
        ),
        migrations.AddField(
            model_name='admin',
            name='registered_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.region'),
        ),
        migrations.AddField(
            model_name='saadditionalcharges',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.gstcode'),
        ),
        migrations.AddField(
            model_name='sacoreservice',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_assignments', to='control_panel.sacoreservice'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='hsn_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.gstcode'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='control_panel.sacoreservice'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargerule',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rules', to='control_panel.serviceprovider'),
        ),
        migrations.AddField(
            model_name='adminservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_service_links', to='control_panel.serviceprovider'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.smsaccount'),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_history', to='control_panel.portaluser'),
        ),
        migrations.AddIndex(
            model_name='funddepositrequest',
            index=models.Index(fields=['utr_ref'], name='txn_fund_de_utr_ref_a0602f_idx'),
        ),
        migrations.AddIndex(
            model_name='funddepositrequest',
            index=models.Index(fields=['status'], name='txn_fund_de_status_4653ee_idx'),
        ),
        migrations.AddIndex(
            model_name='funddepositrequest',
            index=models.Index(fields=['submitted_at'], name='txn_fund_de_submitt_62f123_idx'),
        ),
        migrations.AddIndex(
            model_name='portaluserbalance',
            index=models.Index(fields=['user'], name='portal_user_portal__64715a_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['title', 'region'], name='master_loca_title_3237fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('title', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='chargerule',
            unique_together={('service_provider', 'linked_identifier', 'charge_type', 'charge_beneficiary')},
        ),
        migrations.AlterUniqueTogether(
            name='adminservice',
            unique_together={('admin', 'service', 'provider')},
        ),
    ]
