# Generated by Django 5.2.8 on 2025-12-15 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admincontract',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='control_panel.admin'),
        ),
        migrations.AddField(
            model_name='admincontract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminservice',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_services', to='control_panel.admin'),
        ),
        migrations.AddField(
            model_name='adminservice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargerule',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_charge_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charges',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositbankaccount',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_banks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositbankaccount',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_banks_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gadgetitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_panel.gadgetcategory'),
        ),
        migrations.AddField(
            model_name='gadgetpurchase',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_panel.gadgetitem'),
        ),
        migrations.AddField(
            model_name='gstcode',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gst_entries_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstcode',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_entries_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionalfee',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.gstcode'),
        ),
        migrations.AddField(
            model_name='itemserial',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_panel.gadgetitem'),
        ),
        migrations.AddField(
            model_name='admin',
            name='registered_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.location'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='added_by',
            field=models.ForeignKey(db_column='added_by', on_delete=django.db.models.deletion.CASCADE, related_name='items_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productitem',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='added_by',
            field=models.ForeignKey(db_column='added_by', on_delete=django.db.models.deletion.CASCADE, related_name='categories_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productitemcategory',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.productitemcategory'),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='control_panel.region'),
        ),
        migrations.AddField(
            model_name='admin',
            name='registered_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.region'),
        ),
        migrations.AddField(
            model_name='saadditionalcharges',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.gstcode'),
        ),
        migrations.AddField(
            model_name='sacoreservice',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_assignments', to='control_panel.sacoreservice'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='hsn_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.gstcode'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='control_panel.sacoreservice'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charges',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='control_panel.serviceprovider'),
        ),
        migrations.AddField(
            model_name='chargerule',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rules', to='control_panel.serviceprovider'),
        ),
        migrations.AddField(
            model_name='adminservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_service_links', to='control_panel.serviceprovider'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.smsaccount'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city_name', 'region'], name='master_loca_city_na_428600_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city_name', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='chargerule',
            unique_together={('service_provider', 'linked_identifier', 'charge_type', 'charge_beneficiary')},
        ),
        migrations.AlterUniqueTogether(
            name='adminservice',
            unique_together={('admin', 'service', 'provider')},
        ),
    ]
