# Generated by Django 6.0 on 2025-12-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='master_id',
            new_name='admin_id',
        ),
    ]
