# Generated by Django 5.2.8 on 2025-12-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitConfig',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_per_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_daily_total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('max_monthly_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_daily_transactions', models.PositiveIntegerField(blank=True, null=True)),
                ('max_monthly_transactions', models.PositiveIntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_panel.admin')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_panel.serviceprovider')),
            ],
            options={
                'db_table': 'limit_config',
            },
        ),
    ]
