# Generated by Django 5.2.8 on 2025-12-10 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_additionalfee_documenttemplate_portaluser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaCoreService',
            fields=[
                ('service_key', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, unique=True)),
                ('routing_order', models.JSONField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Core Service',
                'db_table': 'core_services',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(max_length=100, unique=True)),
                ('display_label', models.CharField(max_length=200)),
                ('api_credentials', models.JSONField(blank=True, null=True)),
                ('required_params', models.JSONField(blank=True, null=True)),
                ('tds_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tds_applicable', models.CharField(blank=True, choices=[('WITH_TDS', 'With TDS'), ('WITHOUT_TDS', 'Without TDS')], max_length=20, null=True)),
                ('wallet_type', models.CharField(blank=True, max_length=30, null=True)),
                ('supports_balance_check', models.BooleanField(default=False)),
                ('is_charge_service', models.BooleanField(default=False)),
                ('platform_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('charge_type', models.CharField(blank=True, max_length=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_inactive', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('hsn_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.gstcode')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='control_panel.sacoreservice')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_vendors',
            },
        ),
    ]
