# Generated by Django 6.0 on 2025-12-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_rename_master_id_serviceprovider_admin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='admin_id',
            new_name='sp_id',
        ),
    ]
