# Generated by Django 6.0 on 2025-12-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_rename_admin_id_serviceprovider_sp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemserial',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_panel.productitem'),
        ),
    ]
