# Generated by Django 6.0 on 2025-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_alter_itemserial_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
