# Generated by Django 6.0 on 2025-12-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0006_serviceprovider_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpemail',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpemail',
            name='verify_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
