# Generated by Django 5.2.8 on 2025-12-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
