# Generated by Django 5.2.8 on 2025-12-04 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0002_adminaccount_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminbanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('review_text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('profile_photo', models.ImageField(upload_to='Testimonials/Profile/')),
                ('is_inactive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
