# Generated by Django 5.2.8 on 2025-12-04 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0003_adminbanner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminactivitylog',
            table='admin_activity_log',
        ),
        migrations.AlterModelTable(
            name='adminbanner',
            table='Admin_banners',
        ),
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('overview_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_story', models.TextField(blank=True, null=True)),
                ('core_values', models.TextField(blank=True, null=True)),
                ('leadership_message', models.TextField(blank=True, null=True)),
                ('future_goals', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_overviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aboutus',
                'verbose_name_plural': 'Aboutus',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='ContactSupport',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('issue_title', models.CharField(max_length=300)),
                ('issue_description', models.TextField()),
                ('current_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=300)),
                ('details', models.TextField()),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Latest News Update',
                'db_table': 'hub_latest_news',
                'ordering': ['-publish_date', '-news_id'],
            },
        ),
    ]
