# Generated by Django 5.2.8 on 2025-12-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adcharges',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('charge_mode', models.CharField(choices=[('FLAT', 'Flat'), ('PERCENT', 'Percent')], max_length=10)),
                ('identifier_value', models.PositiveIntegerField(blank=True, null=True)),
                ('min_txn_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('max_txn_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('charge_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('beneficiary', models.CharField(choices=[('PLATFORM', 'Platform Share'), ('PROVIDER', 'Provider Share')], default='PLATFORM', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Commission Rule',
                'db_table': 'provider_commission_rules',
            },
        ),
        migrations.CreateModel(
            name='AdGSTCode',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master_tax_codes',
            },
        ),
        migrations.CreateModel(
            name='AdService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=100, unique=True)),
                ('display_order', models.JSONField(blank=True, default=list)),
                ('short_info', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'platform_services',
                'ordering': ['service_title'],
            },
        ),
        migrations.CreateModel(
            name='AdServiceProvider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('display_name', models.CharField(max_length=200, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('sort_key', models.CharField(blank=True, max_length=10, null=True)),
                ('tds_percent', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('parent_provider', models.PositiveIntegerField(blank=True, null=True)),
                ('mapped_to', models.PositiveIntegerField(blank=True, null=True)),
                ('api_credentials', models.JSONField(blank=True, default=dict)),
                ('required_params', models.JSONField(blank=True, default=list)),
                ('self_managed', models.BooleanField(default=False)),
                ('uses_identifier', models.BooleanField(default=False, help_text='Does this provider use charge_identifier?')),
                ('nature', models.CharField(blank=True, choices=[('RECHARGE', 'Mobile/DTH'), ('BILLPAY', 'Bill Payment'), ('AEPS', 'AEPS'), ('DMT', 'Money Transfer'), ('PAN', 'PAN Card'), ('UTI', 'UTI PSA'), ('OTHERS', 'Others')], max_length=20, null=True)),
                ('wallet_type', models.CharField(blank=True, max_length=30, null=True)),
                ('platform_fee_mode', models.CharField(blank=True, choices=[('FLAT', 'Flat'), ('PERCENT', '%')], max_length=10, null=True)),
                ('platform_fee_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('system_ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('balance_endpoint', models.CharField(blank=True, max_length=100, null=True)),
                ('can_fetch_balance', models.BooleanField(default=False)),
                ('auth_token', models.TextField(blank=True, null=True)),
                ('config_key', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'db_table': 'service_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillerGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant_biller_groups',
            },
        ),
        migrations.CreateModel(
            name='HierarchyLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('prefix', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant_hierarchy',
            },
        ),
        migrations.CreateModel(
            name='OperatorList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=100)),
                ('op_code', models.CharField(max_length=20)),
                ('operator_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tenant_operators',
            },
        ),
        migrations.CreateModel(
            name='PortalUserLog',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(db_index=True, max_length=50)),
                ('auth_token', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expired', models.BooleanField(default=False)),
                ('token_expiry_time', models.DateTimeField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Login Session',
                'db_table': 'portal_user_log',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='SaOperatorCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platform_charge_heads',
            },
        ),
    ]
