# Generated by Django 5.2.8 on 2025-12-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_hub', '0001_initial'),
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcharges',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_rules', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='adgstcode',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='adservice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_updated', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='hsn_sac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_panel.gstcode'),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='admin_hub.adservice'),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_providers', to='control_panel.portaluser'),
        ),
        migrations.AddField(
            model_name='adcharges',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='admin_hub.adserviceprovider'),
        ),
        migrations.AddField(
            model_name='hierarchylevel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_hub.hierarchylevel'),
        ),
        migrations.AddField(
            model_name='portaluserlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='login_sessions', to='control_panel.portaluser'),
        ),
        migrations.AlterUniqueTogether(
            name='adserviceprovider',
            unique_together={('display_name', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='adcharges',
            unique_together={('provider', 'identifier_value', 'transaction_type', 'beneficiary')},
        ),
    ]
