# Generated by Django 5.2.8 on 2025-12-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_hub', '0001_initial'),
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adserviceprovider',
            name='hsn_sac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_panel.gstcode'),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='admin_hub.adservice'),
        ),
        migrations.AddField(
            model_name='adcharges',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='admin_hub.adserviceprovider'),
        ),
        migrations.AddField(
            model_name='funddepositrequest',
            name='linked_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requests', to='control_panel.depositbankaccount'),
        ),
        migrations.AddField(
            model_name='hierarchylevel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_hub.hierarchylevel'),
        ),
        migrations.AddField(
            model_name='holdtransaction',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.adserviceprovider'),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members_created_by_me', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='paymentgatewaybank',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts_added', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='paymentgatewaybank',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_modified', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='memberactionlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='holdtransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='gltrn',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='funddepositrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_requests_reviewed', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='funddepositrequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_requests_made', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_providers', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='adservice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_updated', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='adgstcode',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='adcharges',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_rules', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluserbalance',
            name='user',
            field=models.OneToOneField(blank=True, db_column='portal_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_account', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluserinfo',
            name='city_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='control_panel.location'),
        ),
        migrations.AddField(
            model_name='portaluserinfo',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_created', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluserinfo',
            name='hierarchy_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluserinfo',
            name='state_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='control_panel.region'),
        ),
        migrations.AddField(
            model_name='portaluserinfo',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_details', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluserlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='login_sessions', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='rechargetransaction',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.adserviceprovider'),
        ),
        migrations.AddField(
            model_name='userloginsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='admin_hub.portaluser'),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_history', to='admin_hub.portaluser'),
        ),
        migrations.AddIndex(
            model_name='funddepositrequest',
            index=models.Index(fields=['utr_ref'], name='txn_fund_de_utr_ref_a0602f_idx'),
        ),
        migrations.AddIndex(
            model_name='funddepositrequest',
            index=models.Index(fields=['status'], name='txn_fund_de_status_4653ee_idx'),
        ),
        migrations.AddIndex(
            model_name='funddepositrequest',
            index=models.Index(fields=['submitted_at'], name='txn_fund_de_submitt_62f123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adserviceprovider',
            unique_together={('display_name', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='adcharges',
            unique_together={('provider', 'identifier_value', 'transaction_type', 'beneficiary')},
        ),
        migrations.AddIndex(
            model_name='portaluserbalance',
            index=models.Index(fields=['user'], name='portal_user_portal__64715a_idx'),
        ),
    ]
