from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(PortalUser)
admin.site.register(PortalUserInfo)
admin.site.register(AdService)
admin.site.register(PortalUserBalance)
admin.site.register(MemberActionLog)
admin.site.register(GlTrn)
admin.site.register(WalletHistory)
admin.site.register(PaymentGatewayBank)
admin.site.register(AdServiceProvider)
admin.site.register(Adcharges)
admin.site.register(AdGSTCode)
admin.site.register(PortalUserLog)
admin.site.register(SaOperatorCharge)
admin.site.register(BillerGroup)
admin.site.register(DmtTransferClient)
admin.site.register(UserLoginSession)
admin.site.register(GovernmentChargeLog)
admin.site.register(GlobalBankList)
admin.site.register(RechargeTransaction)
admin.site.register(DmtBankAccount)
admin.site.register(OperatorList)
admin.site.register(HierarchyLevel)
admin.site.register(MoneyTransferLog)
admin.site.register(PaymentGatewayRecord)
admin.site.register(RechargeHistory)
admin.site.register(FundTransferEntry)
admin.site.register(CashfreeKycProfile)
admin.site.register(BillPaymentRecord)
admin.site.register(CashfreePaymentLog)
admin.site.register(PhonePePaymentEntry)
admin.site.register(ElectricityCategory)
admin.site.register(AadhaarVerifyLog)
admin.site.register(ElectricityBillEntry)
admin.site.register(GasCategory)
admin.site.register(GasBillEntry)
admin.site.register(LicPremiumEntry)
admin.site.register(AepsBankList)
admin.site.register(AepsCashLog)
admin.site.register(ServiceIdentifier)
admin.site.register(GlobalBankInstitution)
admin.site.register(BulkPeClientInfo)
admin.site.register(BulkPeCardInfo)
admin.site.register(BulkPeBeneficiaryInfo)
admin.site.register(BulkPayoutRecord)
admin.site.register(AirtelBillEntry)
admin.site.register(BankItAepsRecord)
admin.site.register(MicroAtmEntry)
admin.site.register(PpiTransferLog)
admin.site.register(KhataClient)
admin.site.register(KhataBankAccount)
admin.site.register(KhataTransferEntry)
admin.site.register(AdGadgetCategory)